name 'centos'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures centos'
long_description 'Installs/Configures centos'
version '0.1.0'
issues_url 'https://github.com/narikin/chef_examples/issues'
source_url 'https://github.com/narikin/chef_examples'
